# Generated by Django 5.2.1 on 2025-05-23 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
                ('icone', models.URLField()),
                ('lancamento', models.DateField()),
                ('preco', models.FloatField()),
                ('classificao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LinkComponenete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('descricao', models.CharField()),
                ('Componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_top_pc.componente')),
            ],
        ),
    ]
