# Generated by Django 5.2.1 on 2025-05-23 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_top_pc', '0002_alter_componente_nome_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkComponenete',
            new_name='LinkComponente',
        ),
        migrations.AddField(
            model_name='componente',
            name='tipo',
            field=models.CharField(choices=[('CPU', 'CPU'), ('GPU', 'GPU'), ('Placa-mãe', 'Placa-mãe'), ('RAM', 'RAM'), ('Armazenamento', 'Armazenamento')], default='CPU', max_length=20),
        ),
        migrations.CreateModel(
            name='EstatisticaComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benchmark', models.IntegerField()),
                ('eficiencia_energetica', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_top_pc.componente')),
            ],
        ),
    ]
