# Generated by Django 5.2.1 on 2025-05-30 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_top_pc', '0003_rename_linkcomponenete_linkcomponente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componente',
            old_name='classificao',
            new_name='classificacao',
        ),
    ]
