# Generated by Django 5.2.3 on 2025-06-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_top_pc", "0005_categoria_usuario_endereco_pedido_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(
                blank=True,
                help_text="Imagem do produto",
                null=True,
                upload_to="produtos/",
            ),
        ),
    ]
